name: Docker Image CI

on: [push]

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get the version
      id: vars
      run: |
        echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        echo ${GITHUB_SHA::6} >> properties.yml
    - name: Docker build & push
      run: |
        DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ secrets.IMAGE_NAME }} .
        docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::6}
        docker push ${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::6}
        docker push ${{ secrets.IMAGE_NAME }}:latest
#version: v1.2.3
#gitRevision: 748374385934fd
#    - name: Build the tagged Docker image
#      run: docker build . --file Dockerfile --tag naturalett/playground:${{steps.vars.outputs.tag}}
#    - name: Push the tagged Docker image
#      run: docker push naturalett/playground:${{steps.vars.outputs.tag}}
#    - name: Build the latest Docker image
#      run: docker build . --file Dockerfile --tag naturalett/playground:latest
#    - name: Push the latest Docker image
#      run: docker push naturalett/playground:latest

