name: git-auto-commit

# on:
#   push:
#     branches:
#       - master

on: push

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "TEST_PYPI_PUBLISH=True" >> $GITHUB_ENV
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies for setup
      run: |
        python -m pip install --upgrade pip
        pip install GitPython
    - name: Project versioning
      run: ./version/version.py
    - name: Use git-auto-commit-action
      id: "auto-commit-action"
      uses: ./version/__init__.py

    - name: "no changes detected"
      if: steps.auto-commit-action.outputs.changes_detected == false
      run: "echo \"No changes detected\""

    - name: "changes detected"
      if: steps.auto-commit-action.outputs.changes_detected == true
      run: "echo \"Changes detected\""
      