name: Create Release

on:
  workflow_run:
    workflows: ["Publish package"]
    types: 
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Set env
        run: echo "git_tag=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
      - name: Set2 env2
        run: echo "${{ env.git_tag }} and   $GITHUB_ENV"
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Set3 env3
        run: echo "${{ env.base-ref }} "
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "refs/tags/${{ env.base-ref }}"
          release_name: "Release refs/tags/${{ env.base-ref }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false